### ISSUE TITLE
Linux 64bit ELF agent bug

### ISSUE THREAD

**Issue by rcfontana** [d3vzer0/reternal-quickstart#1]
Error while executing the agent payload.bin file for 64bit ELF.

```
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 5 [running]:
main.StartPulse()
	/reternal-agent/agent/src/corebeacon.go:73 +0x27d
created by main.StartBeacon
	/reternal-agent/agent/src/corebeacon.go:65 +0x37

```

**Comment by d3vzer0** [comment]
Issue occured because the default  beaconing destination was set up to an incorrect url/port. Changed the defaults to match the docker-compose file. Will add proper error handling inside the corebeacon code to quit without an explicit error.
